// Code generated by wsdl2go. DO NOT EDIT.

package tranglo

import (
	"github.com/fiorix/wsdl2go/soap"
)

// Namespace was auto-generated from WSDL.
var Namespace = "http://tempuri.org/"

// NewAPI_Service1Soap creates an initializes a API_Service1Soap.
func NewAPI_Service1Soap(cli *soap.Client) API_Service1Soap {
	return &aPI_Service1Soap{cli}
}

// API_Service1Soap was auto-generated from WSDL
// and defines interface for the remote service. Useful for testing.
type API_Service1Soap interface {
	// Do_BillInquiry was auto-generated from WSDL.
	Do_BillInquiry(Do_BillInquiry *Do_BillInquiry) (*Do_BillInquiryResponse, error)

	// Do_BillPayment was auto-generated from WSDL.
	Do_BillPayment(Do_BillPayment *Do_BillPayment) (*Do_BillPaymentResponse, error)

	// Do_Cancellation was auto-generated from WSDL.
	Do_Cancellation(Do_Cancellation *Do_Cancellation) (*Do_CancellationResponse, error)

	// Do_ChangeName was auto-generated from WSDL.
	Do_ChangeName(Do_ChangeName *Do_ChangeName) (*Do_ChangeNameResponse, error)

	// Do_Transfer was auto-generated from WSDL.
	Do_Transfer(Do_Transfer *Do_Transfer) (*Do_TransferResponse, error)

	// Do_Transfer_Sync was auto-generated from WSDL.
	Do_Transfer_Sync(Do_Transfer_Sync *Do_Transfer_Sync) (*Do_Transfer_SyncResponse, error)

	// Get_Balance was auto-generated from WSDL.
	Get_Balance(Get_Balance *Get_Balance) (*Get_BalanceResponse, error)

	// Get_CancellationStatus was auto-generated from WSDL.
	Get_CancellationStatus(Get_CancellationStatus *Get_CancellationStatus) (*Get_CancellationStatusResponse, error)

	// Get_ChangeNameStatus was auto-generated from WSDL.
	Get_ChangeNameStatus(Get_ChangeNameStatus *Get_ChangeNameStatus) (*Get_ChangeNameStatusResponse, error)

	// Get_Forex was auto-generated from WSDL.
	Get_Forex(Get_Forex *Get_Forex) (*Get_ForexResponse, error)

	// Get_ForexNextRate was auto-generated from WSDL.
	Get_ForexNextRate(Get_ForexNextRate *Get_ForexNextRate) (*Get_ForexNextRateResponse, error)

	// Get_List was auto-generated from WSDL.
	Get_List(Get_List *Get_List) (*Get_ListResponse, error)

	// Get_PayoutCode was auto-generated from WSDL.
	Get_PayoutCode(Get_PayoutCode *Get_PayoutCode) (*Get_PayoutCodeResponse, error)

	// Get_TrxFee was auto-generated from WSDL.
	Get_TrxFee(Get_TrxFee *Get_TrxFee) (*Get_TrxFeeResponse, error)

	// Get_TrxStatus was auto-generated from WSDL.
	Get_TrxStatus(Get_TrxStatus *Get_TrxStatus) (*Get_TrxStatusResponse, error)

	// Get_Validation was auto-generated from WSDL.
	Get_Validation(Get_Validation *Get_Validation) (*Get_ValidationResponse, error)

	// Get_Watchlist was auto-generated from WSDL.
	Get_Watchlist(Get_Watchlist *Get_Watchlist) (*Get_WatchlistResponse, error)

	// Ping was auto-generated from WSDL.
	Ping(Ping *Ping) (*PingResponse, error)
}

// Do_BillInquiry was auto-generated from WSDL.
type Do_BillInquiry struct {
	RspSign     *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	UID         *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD         *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	TransID     *string `xml:"transID,omitempty" json:"transID,omitempty" yaml:"transID,omitempty"`
	SIdType     int     `xml:"sIdType" json:"sIdType" yaml:"sIdType"`
	SIdNum      *string `xml:"sIdNum,omitempty" json:"sIdNum,omitempty" yaml:"sIdNum,omitempty"`
	SFirstName  *string `xml:"sFirstName,omitempty" json:"sFirstName,omitempty" yaml:"sFirstName,omitempty"`
	SLastName   *string `xml:"sLastName,omitempty" json:"sLastName,omitempty" yaml:"sLastName,omitempty"`
	BCountry    *string `xml:"bCountry,omitempty" json:"bCountry,omitempty" yaml:"bCountry,omitempty"`
	BCurrency   *string `xml:"bCurrency,omitempty" json:"bCurrency,omitempty" yaml:"bCurrency,omitempty"`
	BAmount     float64 `xml:"bAmount" json:"bAmount" yaml:"bAmount"`
	BIssuerCode *string `xml:"bIssuerCode,omitempty" json:"bIssuerCode,omitempty" yaml:"bIssuerCode,omitempty"`
	BAccNum     *string `xml:"bAccNum,omitempty" json:"bAccNum,omitempty" yaml:"bAccNum,omitempty"`
}

// Do_BillInquiryResponse was auto-generated from WSDL.
type Do_BillInquiryResponse struct {
	Do_BillInquiryResult *interface{} `xml:"Do_BillInquiryResult,omitempty" json:"Do_BillInquiryResult,omitempty" yaml:"Do_BillInquiryResult,omitempty"`
}

// Do_BillPayment was auto-generated from WSDL.
type Do_BillPayment struct {
	RspSign        *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	UID            *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD            *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	UIDBranch      *string `xml:"UIDBranch,omitempty" json:"UIDBranch,omitempty" yaml:"UIDBranch,omitempty"`
	TransID        *string `xml:"transID,omitempty" json:"transID,omitempty" yaml:"transID,omitempty"`
	SFirstName     *string `xml:"sFirstName,omitempty" json:"sFirstName,omitempty" yaml:"sFirstName,omitempty"`
	SLastName      *string `xml:"sLastName,omitempty" json:"sLastName,omitempty" yaml:"sLastName,omitempty"`
	SIdType        int     `xml:"sIdType" json:"sIdType" yaml:"sIdType"`
	SIdNum         *string `xml:"sIdNum,omitempty" json:"sIdNum,omitempty" yaml:"sIdNum,omitempty"`
	SIdExpiry      *string `xml:"sIdExpiry,omitempty" json:"sIdExpiry,omitempty" yaml:"sIdExpiry,omitempty"`
	SContactNum    *string `xml:"sContactNum,omitempty" json:"sContactNum,omitempty" yaml:"sContactNum,omitempty"`
	SEmail         *string `xml:"sEmail,omitempty" json:"sEmail,omitempty" yaml:"sEmail,omitempty"`
	SCountry       *string `xml:"sCountry,omitempty" json:"sCountry,omitempty" yaml:"sCountry,omitempty"`
	SCurrency      *string `xml:"sCurrency,omitempty" json:"sCurrency,omitempty" yaml:"sCurrency,omitempty"`
	BCountry       *string `xml:"bCountry,omitempty" json:"bCountry,omitempty" yaml:"bCountry,omitempty"`
	BCurrency      *string `xml:"bCurrency,omitempty" json:"bCurrency,omitempty" yaml:"bCurrency,omitempty"`
	BAmount        float64 `xml:"bAmount" json:"bAmount" yaml:"bAmount"`
	BIssuerCode    *string `xml:"bIssuerCode,omitempty" json:"bIssuerCode,omitempty" yaml:"bIssuerCode,omitempty"`
	BAccNum        *string `xml:"bAccNum,omitempty" json:"bAccNum,omitempty" yaml:"bAccNum,omitempty"`
	BBillNum       *string `xml:"bBillNum,omitempty" json:"bBillNum,omitempty" yaml:"bBillNum,omitempty"`
	BAccName       *string `xml:"bAccName,omitempty" json:"bAccName,omitempty" yaml:"bAccName,omitempty"`
	BStatementDate *string `xml:"bStatementDate,omitempty" json:"bStatementDate,omitempty" yaml:"bStatementDate,omitempty"`
	BDueDate       *string `xml:"bDueDate,omitempty" json:"bDueDate,omitempty" yaml:"bDueDate,omitempty"`
	BBillType      *string `xml:"bBillType,omitempty" json:"bBillType,omitempty" yaml:"bBillType,omitempty"`
	BCustomInfo1   *string `xml:"bCustomInfo1,omitempty" json:"bCustomInfo1,omitempty" yaml:"bCustomInfo1,omitempty"`
	BCustomInfo2   *string `xml:"bCustomInfo2,omitempty" json:"bCustomInfo2,omitempty" yaml:"bCustomInfo2,omitempty"`
	BCustomInfo3   *string `xml:"bCustomInfo3,omitempty" json:"bCustomInfo3,omitempty" yaml:"bCustomInfo3,omitempty"`
	BCustomInfo4   *string `xml:"bCustomInfo4,omitempty" json:"bCustomInfo4,omitempty" yaml:"bCustomInfo4,omitempty"`
	BCustomInfo5   *string `xml:"bCustomInfo5,omitempty" json:"bCustomInfo5,omitempty" yaml:"bCustomInfo5,omitempty"`
	BCustomInfo6   *string `xml:"bCustomInfo6,omitempty" json:"bCustomInfo6,omitempty" yaml:"bCustomInfo6,omitempty"`
	BCustomInfo7   *string `xml:"bCustomInfo7,omitempty" json:"bCustomInfo7,omitempty" yaml:"bCustomInfo7,omitempty"`
	BCustomInfo8   *string `xml:"bCustomInfo8,omitempty" json:"bCustomInfo8,omitempty" yaml:"bCustomInfo8,omitempty"`
	BCustomInfo9   *string `xml:"bCustomInfo9,omitempty" json:"bCustomInfo9,omitempty" yaml:"bCustomInfo9,omitempty"`
	BCustomInfo10  *string `xml:"bCustomInfo10,omitempty" json:"bCustomInfo10,omitempty" yaml:"bCustomInfo10,omitempty"`
}

// Do_BillPaymentResponse was auto-generated from WSDL.
type Do_BillPaymentResponse struct {
	Do_BillPaymentResult *interface{} `xml:"Do_BillPaymentResult,omitempty" json:"Do_BillPaymentResult,omitempty" yaml:"Do_BillPaymentResult,omitempty"`
}

// Do_Cancellation was auto-generated from WSDL.
type Do_Cancellation struct {
	UID                  *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD                  *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	RspSign              *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	TransID              *string `xml:"transID,omitempty" json:"transID,omitempty" yaml:"transID,omitempty"`
	TrangloTransactionId *string `xml:"trangloTransactionId,omitempty" json:"trangloTransactionId,omitempty" yaml:"trangloTransactionId,omitempty"`
}

// Do_CancellationResponse was auto-generated from WSDL.
type Do_CancellationResponse struct {
	Do_CancellationResult *interface{} `xml:"Do_CancellationResult,omitempty" json:"Do_CancellationResult,omitempty" yaml:"Do_CancellationResult,omitempty"`
}

// Do_ChangeName was auto-generated from WSDL.
type Do_ChangeName struct {
	UID                  *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD                  *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	RspSign              *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	TransID              *string `xml:"transID,omitempty" json:"transID,omitempty" yaml:"transID,omitempty"`
	TrangloTransactionId *string `xml:"trangloTransactionId,omitempty" json:"trangloTransactionId,omitempty" yaml:"trangloTransactionId,omitempty"`
	BeneFirstName        *string `xml:"beneFirstName,omitempty" json:"beneFirstName,omitempty" yaml:"beneFirstName,omitempty"`
	BeneLastName         *string `xml:"beneLastName,omitempty" json:"beneLastName,omitempty" yaml:"beneLastName,omitempty"`
}

// Do_ChangeNameResponse was auto-generated from WSDL.
type Do_ChangeNameResponse struct {
	Do_ChangeNameResult *interface{} `xml:"Do_ChangeNameResult,omitempty" json:"Do_ChangeNameResult,omitempty" yaml:"Do_ChangeNameResult,omitempty"`
}

// Do_Transfer was auto-generated from WSDL.
type Do_Transfer struct {
	RspSign        *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	UID            *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD            *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	UIDBranch      *string `xml:"UIDBranch,omitempty" json:"UIDBranch,omitempty" yaml:"UIDBranch,omitempty"`
	TransID        *string `xml:"transID,omitempty" json:"transID,omitempty" yaml:"transID,omitempty"`
	SFirstName     *string `xml:"sFirstName,omitempty" json:"sFirstName,omitempty" yaml:"sFirstName,omitempty"`
	SLastName      *string `xml:"sLastName,omitempty" json:"sLastName,omitempty" yaml:"sLastName,omitempty"`
	SIdType        int     `xml:"sIdType" json:"sIdType" yaml:"sIdType"`
	SIdNum         *string `xml:"sIdNum,omitempty" json:"sIdNum,omitempty" yaml:"sIdNum,omitempty"`
	SIdExpiry      *string `xml:"sIdExpiry,omitempty" json:"sIdExpiry,omitempty" yaml:"sIdExpiry,omitempty"`
	SContactNum    *string `xml:"sContactNum,omitempty" json:"sContactNum,omitempty" yaml:"sContactNum,omitempty"`
	SOccupation    *string `xml:"sOccupation,omitempty" json:"sOccupation,omitempty" yaml:"sOccupation,omitempty"`
	SFundSource    *string `xml:"sFundSource,omitempty" json:"sFundSource,omitempty" yaml:"sFundSource,omitempty"`
	SBirthDate     *string `xml:"sBirthDate,omitempty" json:"sBirthDate,omitempty" yaml:"sBirthDate,omitempty"`
	SEmail         *string `xml:"sEmail,omitempty" json:"sEmail,omitempty" yaml:"sEmail,omitempty"`
	SAddress       *string `xml:"sAddress,omitempty" json:"sAddress,omitempty" yaml:"sAddress,omitempty"`
	SCity          *string `xml:"sCity,omitempty" json:"sCity,omitempty" yaml:"sCity,omitempty"`
	SPostCode      *string `xml:"sPostCode,omitempty" json:"sPostCode,omitempty" yaml:"sPostCode,omitempty"`
	SCountry       *string `xml:"sCountry,omitempty" json:"sCountry,omitempty" yaml:"sCountry,omitempty"`
	SCurrency      *string `xml:"sCurrency,omitempty" json:"sCurrency,omitempty" yaml:"sCurrency,omitempty"`
	BCountry       *string `xml:"bCountry,omitempty" json:"bCountry,omitempty" yaml:"bCountry,omitempty"`
	BCurrency      *string `xml:"bCurrency,omitempty" json:"bCurrency,omitempty" yaml:"bCurrency,omitempty"`
	TrxValue       float64 `xml:"trxValue" json:"trxValue" yaml:"trxValue"`
	BFirstName     *string `xml:"bFirstName,omitempty" json:"bFirstName,omitempty" yaml:"bFirstName,omitempty"`
	BLastName      *string `xml:"bLastName,omitempty" json:"bLastName,omitempty" yaml:"bLastName,omitempty"`
	BAccType       int     `xml:"bAccType" json:"bAccType" yaml:"bAccType"`
	BIssuerCode    *string `xml:"bIssuerCode,omitempty" json:"bIssuerCode,omitempty" yaml:"bIssuerCode,omitempty"`
	BankProvince   *string `xml:"BankProvince,omitempty" json:"BankProvince,omitempty" yaml:"BankProvince,omitempty"`
	BankCity       *string `xml:"BankCity,omitempty" json:"BankCity,omitempty" yaml:"BankCity,omitempty"`
	BankBranchName *string `xml:"BankBranchName,omitempty" json:"BankBranchName,omitempty" yaml:"BankBranchName,omitempty"`
	BankBranchCode *string `xml:"BankBranchCode,omitempty" json:"BankBranchCode,omitempty" yaml:"BankBranchCode,omitempty"`
	BAccNum        *string `xml:"bAccNum,omitempty" json:"bAccNum,omitempty" yaml:"bAccNum,omitempty"`
	BIdType        int     `xml:"bIdType" json:"bIdType" yaml:"bIdType"`
	BIdNum         *string `xml:"bIdNum,omitempty" json:"bIdNum,omitempty" yaml:"bIdNum,omitempty"`
	BContactNum    *string `xml:"bContactNum,omitempty" json:"bContactNum,omitempty" yaml:"bContactNum,omitempty"`
	Relationship   *string `xml:"Relationship,omitempty" json:"Relationship,omitempty" yaml:"Relationship,omitempty"`
	BAddress       *string `xml:"bAddress,omitempty" json:"bAddress,omitempty" yaml:"bAddress,omitempty"`
	BCity          *string `xml:"bCity,omitempty" json:"bCity,omitempty" yaml:"bCity,omitempty"`
	BPostCode      *string `xml:"bPostCode,omitempty" json:"bPostCode,omitempty" yaml:"bPostCode,omitempty"`
	BEmail         *string `xml:"bEmail,omitempty" json:"bEmail,omitempty" yaml:"bEmail,omitempty"`
	BProvinceCode  *string `xml:"bProvinceCode,omitempty" json:"bProvinceCode,omitempty" yaml:"bProvinceCode,omitempty"`
	BRegencyCode   *string `xml:"bRegencyCode,omitempty" json:"bRegencyCode,omitempty" yaml:"bRegencyCode,omitempty"`
	BPayoutID      *string `xml:"bPayoutID,omitempty" json:"bPayoutID,omitempty" yaml:"bPayoutID,omitempty"`
	BPayoutPIN     *string `xml:"bPayoutPIN,omitempty" json:"bPayoutPIN,omitempty" yaml:"bPayoutPIN,omitempty"`
	SAmount        float64 `xml:"sAmount" json:"sAmount" yaml:"sAmount"`
	FR_Key         *string `xml:"FR_Key,omitempty" json:"FR_Key,omitempty" yaml:"FR_Key,omitempty"`
	BPurposeCode   int     `xml:"bPurposeCode" json:"bPurposeCode" yaml:"bPurposeCode"`
	BBirthDate     *string `xml:"bBirthDate,omitempty" json:"bBirthDate,omitempty" yaml:"bBirthDate,omitempty"`
}

// Do_TransferResponse was auto-generated from WSDL.
type Do_TransferResponse struct {
	Do_TransferResult *interface{} `xml:"Do_TransferResult,omitempty" json:"Do_TransferResult,omitempty" yaml:"Do_TransferResult,omitempty"`
}

// Do_Transfer_Sync was auto-generated from WSDL.
type Do_Transfer_Sync struct {
	RspSign       *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	UID           *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD           *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	UIDBranch     *string `xml:"UIDBranch,omitempty" json:"UIDBranch,omitempty" yaml:"UIDBranch,omitempty"`
	TransID       *string `xml:"transID,omitempty" json:"transID,omitempty" yaml:"transID,omitempty"`
	SFirstName    *string `xml:"sFirstName,omitempty" json:"sFirstName,omitempty" yaml:"sFirstName,omitempty"`
	SLastName     *string `xml:"sLastName,omitempty" json:"sLastName,omitempty" yaml:"sLastName,omitempty"`
	SIdType       int     `xml:"sIdType" json:"sIdType" yaml:"sIdType"`
	SIdNum        *string `xml:"sIdNum,omitempty" json:"sIdNum,omitempty" yaml:"sIdNum,omitempty"`
	SIdExpiry     *string `xml:"sIdExpiry,omitempty" json:"sIdExpiry,omitempty" yaml:"sIdExpiry,omitempty"`
	SContactNum   *string `xml:"sContactNum,omitempty" json:"sContactNum,omitempty" yaml:"sContactNum,omitempty"`
	SOccupation   *string `xml:"sOccupation,omitempty" json:"sOccupation,omitempty" yaml:"sOccupation,omitempty"`
	SFundSource   *string `xml:"sFundSource,omitempty" json:"sFundSource,omitempty" yaml:"sFundSource,omitempty"`
	SBirthDate    *string `xml:"sBirthDate,omitempty" json:"sBirthDate,omitempty" yaml:"sBirthDate,omitempty"`
	SEmail        *string `xml:"sEmail,omitempty" json:"sEmail,omitempty" yaml:"sEmail,omitempty"`
	SAddress      *string `xml:"sAddress,omitempty" json:"sAddress,omitempty" yaml:"sAddress,omitempty"`
	SCity         *string `xml:"sCity,omitempty" json:"sCity,omitempty" yaml:"sCity,omitempty"`
	SPostCode     *string `xml:"sPostCode,omitempty" json:"sPostCode,omitempty" yaml:"sPostCode,omitempty"`
	SCountry      *string `xml:"sCountry,omitempty" json:"sCountry,omitempty" yaml:"sCountry,omitempty"`
	SCurrency     *string `xml:"sCurrency,omitempty" json:"sCurrency,omitempty" yaml:"sCurrency,omitempty"`
	BCountry      *string `xml:"bCountry,omitempty" json:"bCountry,omitempty" yaml:"bCountry,omitempty"`
	BCurrency     *string `xml:"bCurrency,omitempty" json:"bCurrency,omitempty" yaml:"bCurrency,omitempty"`
	TrxValue      float64 `xml:"trxValue" json:"trxValue" yaml:"trxValue"`
	BFirstName    *string `xml:"bFirstName,omitempty" json:"bFirstName,omitempty" yaml:"bFirstName,omitempty"`
	BLastName     *string `xml:"bLastName,omitempty" json:"bLastName,omitempty" yaml:"bLastName,omitempty"`
	BAccType      int     `xml:"bAccType" json:"bAccType" yaml:"bAccType"`
	BIssuerCode   *string `xml:"bIssuerCode,omitempty" json:"bIssuerCode,omitempty" yaml:"bIssuerCode,omitempty"`
	BAccNum       *string `xml:"bAccNum,omitempty" json:"bAccNum,omitempty" yaml:"bAccNum,omitempty"`
	BIdType       int     `xml:"bIdType" json:"bIdType" yaml:"bIdType"`
	BIdNum        *string `xml:"bIdNum,omitempty" json:"bIdNum,omitempty" yaml:"bIdNum,omitempty"`
	BContactNum   *string `xml:"bContactNum,omitempty" json:"bContactNum,omitempty" yaml:"bContactNum,omitempty"`
	Relationship  *string `xml:"Relationship,omitempty" json:"Relationship,omitempty" yaml:"Relationship,omitempty"`
	BAddress      *string `xml:"bAddress,omitempty" json:"bAddress,omitempty" yaml:"bAddress,omitempty"`
	BCity         *string `xml:"bCity,omitempty" json:"bCity,omitempty" yaml:"bCity,omitempty"`
	BPostCode     *string `xml:"bPostCode,omitempty" json:"bPostCode,omitempty" yaml:"bPostCode,omitempty"`
	BEmail        *string `xml:"bEmail,omitempty" json:"bEmail,omitempty" yaml:"bEmail,omitempty"`
	BProvinceCode *string `xml:"bProvinceCode,omitempty" json:"bProvinceCode,omitempty" yaml:"bProvinceCode,omitempty"`
	BRegencyCode  *string `xml:"bRegencyCode,omitempty" json:"bRegencyCode,omitempty" yaml:"bRegencyCode,omitempty"`
	BPayoutID     *string `xml:"bPayoutID,omitempty" json:"bPayoutID,omitempty" yaml:"bPayoutID,omitempty"`
	BPayoutPIN    *string `xml:"bPayoutPIN,omitempty" json:"bPayoutPIN,omitempty" yaml:"bPayoutPIN,omitempty"`
}

// Do_Transfer_SyncResponse was auto-generated from WSDL.
type Do_Transfer_SyncResponse struct {
	Do_Transfer_SyncResult *interface{} `xml:"Do_Transfer_SyncResult,omitempty" json:"Do_Transfer_SyncResult,omitempty" yaml:"Do_Transfer_SyncResult,omitempty"`
}

// Get_Balance was auto-generated from WSDL.
type Get_Balance struct {
	UID *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
}

// Get_BalanceResponse was auto-generated from WSDL.
//<Get_BalanceResult>
//	<string xmlns="http://tempuri.org/">
//		<LastBal>0.00</LastBal>
//	</string>
//</Get_BalanceResult>
type Get_BalanceResponse struct {
	Get_BalanceResult *Get_BalanceResult `xml:"Get_BalanceResult,omitempty" json:"Get_BalanceResult,omitempty" yaml:"Get_BalanceResult,omitempty"`
	//Get_BalanceResult interface{} `xml:"Get_BalanceResult,omitempty" json:"Get_BalanceResult,omitempty" yaml:"Get_BalanceResult,omitempty"`
}

type Get_BalanceResult struct {
	String *String `xml:"http://tempuri.org/ string,omitempty" json:"string,omitempty" yaml:"string,omitempty"`
}

type String struct {
	LastBal float64 `xml:"LastBal,omitempty" json:"LastBal,omitempty" yaml:"LastBal,omitempty"`
}


// Get_CancellationStatus was auto-generated from WSDL.
type Get_CancellationStatus struct {
	UID            *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD            *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	RspSign        *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	CancellationId *string `xml:"cancellationId,omitempty" json:"cancellationId,omitempty" yaml:"cancellationId,omitempty"`
}

// Get_CancellationStatusResponse was auto-generated from WSDL.
type Get_CancellationStatusResponse struct {
	Get_CancellationStatusResult *interface{} `xml:"Get_CancellationStatusResult,omitempty" json:"Get_CancellationStatusResult,omitempty" yaml:"Get_CancellationStatusResult,omitempty"`
}

// Get_ChangeNameStatus was auto-generated from WSDL.
type Get_ChangeNameStatus struct {
	UID      *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD      *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	RspSign  *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	ChangeId *string `xml:"changeId,omitempty" json:"changeId,omitempty" yaml:"changeId,omitempty"`
}

// Get_ChangeNameStatusResponse was auto-generated from WSDL.
type Get_ChangeNameStatusResponse struct {
	Get_ChangeNameStatusResult *interface{} `xml:"Get_ChangeNameStatusResult,omitempty" json:"Get_ChangeNameStatusResult,omitempty" yaml:"Get_ChangeNameStatusResult,omitempty"`
}

// Get_Forex was auto-generated from WSDL.
type Get_Forex struct {
	RspSign  *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	UID      *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD      *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	CurrFrom *string `xml:"CurrFrom,omitempty" json:"CurrFrom,omitempty" yaml:"CurrFrom,omitempty"`
	CurrTo   *string `xml:"CurrTo,omitempty" json:"CurrTo,omitempty" yaml:"CurrTo,omitempty"`
}

// Get_ForexNextRate was auto-generated from WSDL.
type Get_ForexNextRate struct {
	RspSign  *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	UID      *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD      *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	CurrFrom *string `xml:"CurrFrom,omitempty" json:"CurrFrom,omitempty" yaml:"CurrFrom,omitempty"`
	CurrTo   *string `xml:"CurrTo,omitempty" json:"CurrTo,omitempty" yaml:"CurrTo,omitempty"`
}

// Get_ForexNextRateResponse was auto-generated from WSDL.
type Get_ForexNextRateResponse struct {
	Get_ForexNextRateResult *interface{} `xml:"Get_ForexNextRateResult,omitempty" json:"Get_ForexNextRateResult,omitempty" yaml:"Get_ForexNextRateResult,omitempty"`
}

// Get_ForexResponse was auto-generated from WSDL.
type Get_ForexResponse struct {
	Get_ForexResult *interface{} `xml:"Get_ForexResult,omitempty" json:"Get_ForexResult,omitempty" yaml:"Get_ForexResult,omitempty"`
}

// Get_List was auto-generated from WSDL.
type Get_List struct {
	UID      *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD      *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	ListName *string `xml:"ListName,omitempty" json:"ListName,omitempty" yaml:"ListName,omitempty"`
}

// Get_ListResponse was auto-generated from WSDL.
type Get_ListResponse struct {
	Get_ListResult struct{
		String struct{
			List string
		} `xml:"http://tempuri.org/ string,omitempty" json:"string,omitempty" yaml:"string,omitempty"`
	} `xml:"Get_ListResult,omitempty" json:"Get_ListResult,omitempty" yaml:"Get_ListResult,omitempty"`
}

// Get_PayoutCode was auto-generated from WSDL.
type Get_PayoutCode struct {
	UID         *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD         *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	RspSign     *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	RequestId   *string `xml:"requestId,omitempty" json:"requestId,omitempty" yaml:"requestId,omitempty"`
	CountryCode *string `xml:"countryCode,omitempty" json:"countryCode,omitempty" yaml:"countryCode,omitempty"`
	PreBookQty  int     `xml:"preBookQty" json:"preBookQty" yaml:"preBookQty"`
}

// Get_PayoutCodeResponse was auto-generated from WSDL.
type Get_PayoutCodeResponse struct {
	Get_PayoutCodeResult *interface{} `xml:"Get_PayoutCodeResult,omitempty" json:"Get_PayoutCodeResult,omitempty" yaml:"Get_PayoutCodeResult,omitempty"`
}

// Get_TrxFee was auto-generated from WSDL.
type Get_TrxFee struct {
	UID      *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD      *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	BAccType int     `xml:"bAccType" json:"bAccType" yaml:"bAccType"`
	CurrFrom *string `xml:"currFrom,omitempty" json:"currFrom,omitempty" yaml:"currFrom,omitempty"`
	CurrTo   *string `xml:"currTo,omitempty" json:"currTo,omitempty" yaml:"currTo,omitempty"`
	TrxValue float64 `xml:"trxValue" json:"trxValue" yaml:"trxValue"`
}

// Get_TrxFeeResponse was auto-generated from WSDL.
type Get_TrxFeeResponse struct {
	Get_TrxFeeResult *interface{} `xml:"Get_TrxFeeResult,omitempty" json:"Get_TrxFeeResult,omitempty" yaml:"Get_TrxFeeResult,omitempty"`
}

// Get_TrxStatus was auto-generated from WSDL.
type Get_TrxStatus struct {
	RspSign *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	UID     *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD     *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	GTN     *string `xml:"GTN,omitempty" json:"GTN,omitempty" yaml:"GTN,omitempty"`
	TransID *string `xml:"transID,omitempty" json:"transID,omitempty" yaml:"transID,omitempty"`
}

// Get_TrxStatusResponse was auto-generated from WSDL.
type Get_TrxStatusResponse struct {
	Get_TrxStatusResult *interface{} `xml:"Get_TrxStatusResult,omitempty" json:"Get_TrxStatusResult,omitempty" yaml:"Get_TrxStatusResult,omitempty"`
}

// Get_Validation was auto-generated from WSDL.
type Get_Validation struct {
	RspSign     *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	UID         *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD         *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	TransID     *string `xml:"transID,omitempty" json:"transID,omitempty" yaml:"transID,omitempty"`
	SIdType     int     `xml:"sIdType" json:"sIdType" yaml:"sIdType"`
	SIdNum      *string `xml:"sIdNum,omitempty" json:"sIdNum,omitempty" yaml:"sIdNum,omitempty"`
	SFirstName  *string `xml:"sFirstName,omitempty" json:"sFirstName,omitempty" yaml:"sFirstName,omitempty"`
	SLastName   *string `xml:"sLastName,omitempty" json:"sLastName,omitempty" yaml:"sLastName,omitempty"`
	BFirstName  *string `xml:"bFirstName,omitempty" json:"bFirstName,omitempty" yaml:"bFirstName,omitempty"`
	BLastName   *string `xml:"bLastName,omitempty" json:"bLastName,omitempty" yaml:"bLastName,omitempty"`
	BCountry    *string `xml:"bCountry,omitempty" json:"bCountry,omitempty" yaml:"bCountry,omitempty"`
	BAccType    int     `xml:"bAccType" json:"bAccType" yaml:"bAccType"`
	BIssuerCode *string `xml:"bIssuerCode,omitempty" json:"bIssuerCode,omitempty" yaml:"bIssuerCode,omitempty"`
	BAccNum     *string `xml:"bAccNum,omitempty" json:"bAccNum,omitempty" yaml:"bAccNum,omitempty"`
	TrxValue    float64 `xml:"trxValue" json:"trxValue" yaml:"trxValue"`
}

// Get_ValidationResponse was auto-generated from WSDL.
type Get_ValidationResponse struct {
	Get_ValidationResult *interface{} `xml:"Get_ValidationResult,omitempty" json:"Get_ValidationResult,omitempty" yaml:"Get_ValidationResult,omitempty"`
}

// Get_Watchlist was auto-generated from WSDL.
type Get_Watchlist struct {
	RspSign     *string `xml:"rspSign,omitempty" json:"rspSign,omitempty" yaml:"rspSign,omitempty"`
	UID         *string `xml:"UID,omitempty" json:"UID,omitempty" yaml:"UID,omitempty"`
	PWD         *string `xml:"PWD,omitempty" json:"PWD,omitempty" yaml:"PWD,omitempty"`
	UIDBranch   *string `xml:"UIDBranch,omitempty" json:"UIDBranch,omitempty" yaml:"UIDBranch,omitempty"`
	FirstName   *string `xml:"FirstName,omitempty" json:"FirstName,omitempty" yaml:"FirstName,omitempty"`
	LastName    *string `xml:"LastName,omitempty" json:"LastName,omitempty" yaml:"LastName,omitempty"`
	Nationality *string `xml:"Nationality,omitempty" json:"Nationality,omitempty" yaml:"Nationality,omitempty"`
	PassportNo  *string `xml:"PassportNo,omitempty" json:"PassportNo,omitempty" yaml:"PassportNo,omitempty"`
}

// Get_WatchlistResponse was auto-generated from WSDL.
type Get_WatchlistResponse struct {
	Get_WatchlistResult *interface{} `xml:"Get_WatchlistResult,omitempty" json:"Get_WatchlistResult,omitempty" yaml:"Get_WatchlistResult,omitempty"`
}

// Ping was auto-generated from WSDL.
type Ping struct {
}

// PingResponse was auto-generated from WSDL.
type PingResponse struct {
	PingResult int `xml:"PingResult" json:"PingResult" yaml:"PingResult"`
}

// Operation wrapper for Do_BillInquiry.
// OperationDo_BillInquirySoapIn was auto-generated from WSDL.
type OperationDo_BillInquirySoapIn struct {
	Do_BillInquiry *Do_BillInquiry `xml:"Do_BillInquiry,omitempty" json:"Do_BillInquiry,omitempty" yaml:"Do_BillInquiry,omitempty"`
}

// Operation wrapper for Do_BillInquiry.
// OperationDo_BillInquirySoapOut was auto-generated from WSDL.
type OperationDo_BillInquirySoapOut struct {
	Do_BillInquiryResponse *Do_BillInquiryResponse `xml:"Do_BillInquiryResponse,omitempty" json:"Do_BillInquiryResponse,omitempty" yaml:"Do_BillInquiryResponse,omitempty"`
}

// Operation wrapper for Do_BillPayment.
// OperationDo_BillPaymentSoapIn was auto-generated from WSDL.
type OperationDo_BillPaymentSoapIn struct {
	Do_BillPayment *Do_BillPayment `xml:"Do_BillPayment,omitempty" json:"Do_BillPayment,omitempty" yaml:"Do_BillPayment,omitempty"`
}

// Operation wrapper for Do_BillPayment.
// OperationDo_BillPaymentSoapOut was auto-generated from WSDL.
type OperationDo_BillPaymentSoapOut struct {
	Do_BillPaymentResponse *Do_BillPaymentResponse `xml:"Do_BillPaymentResponse,omitempty" json:"Do_BillPaymentResponse,omitempty" yaml:"Do_BillPaymentResponse,omitempty"`
}

// Operation wrapper for Do_Cancellation.
// OperationDo_CancellationSoapIn was auto-generated from WSDL.
type OperationDo_CancellationSoapIn struct {
	Do_Cancellation *Do_Cancellation `xml:"Do_Cancellation,omitempty" json:"Do_Cancellation,omitempty" yaml:"Do_Cancellation,omitempty"`
}

// Operation wrapper for Do_Cancellation.
// OperationDo_CancellationSoapOut was auto-generated from WSDL.
type OperationDo_CancellationSoapOut struct {
	Do_CancellationResponse *Do_CancellationResponse `xml:"Do_CancellationResponse,omitempty" json:"Do_CancellationResponse,omitempty" yaml:"Do_CancellationResponse,omitempty"`
}

// Operation wrapper for Do_ChangeName.
// OperationDo_ChangeNameSoapIn was auto-generated from WSDL.
type OperationDo_ChangeNameSoapIn struct {
	Do_ChangeName *Do_ChangeName `xml:"Do_ChangeName,omitempty" json:"Do_ChangeName,omitempty" yaml:"Do_ChangeName,omitempty"`
}

// Operation wrapper for Do_ChangeName.
// OperationDo_ChangeNameSoapOut was auto-generated from WSDL.
type OperationDo_ChangeNameSoapOut struct {
	Do_ChangeNameResponse *Do_ChangeNameResponse `xml:"Do_ChangeNameResponse,omitempty" json:"Do_ChangeNameResponse,omitempty" yaml:"Do_ChangeNameResponse,omitempty"`
}

// Operation wrapper for Do_Transfer.
// OperationDo_TransferSoapIn was auto-generated from WSDL.
type OperationDo_TransferSoapIn struct {
	Do_Transfer *Do_Transfer `xml:"Do_Transfer,omitempty" json:"Do_Transfer,omitempty" yaml:"Do_Transfer,omitempty"`
}

// Operation wrapper for Do_Transfer.
// OperationDo_TransferSoapOut was auto-generated from WSDL.
type OperationDo_TransferSoapOut struct {
	Do_TransferResponse *Do_TransferResponse `xml:"Do_TransferResponse,omitempty" json:"Do_TransferResponse,omitempty" yaml:"Do_TransferResponse,omitempty"`
}

// Operation wrapper for Do_Transfer_Sync.
// OperationDo_Transfer_SyncSoapIn was auto-generated from WSDL.
type OperationDo_Transfer_SyncSoapIn struct {
	Do_Transfer_Sync *Do_Transfer_Sync `xml:"Do_Transfer_Sync,omitempty" json:"Do_Transfer_Sync,omitempty" yaml:"Do_Transfer_Sync,omitempty"`
}

// Operation wrapper for Do_Transfer_Sync.
// OperationDo_Transfer_SyncSoapOut was auto-generated from WSDL.
type OperationDo_Transfer_SyncSoapOut struct {
	Do_Transfer_SyncResponse *Do_Transfer_SyncResponse `xml:"Do_Transfer_SyncResponse,omitempty" json:"Do_Transfer_SyncResponse,omitempty" yaml:"Do_Transfer_SyncResponse,omitempty"`
}

// Operation wrapper for Get_Balance.
// OperationGet_BalanceSoapIn was auto-generated from WSDL.
type OperationGet_BalanceSoapIn struct {
	Get_Balance *Get_Balance `xml:"http://tempuri.org/ Get_Balance,omitempty" json:"Get_Balance,omitempty" yaml:"Get_Balance,omitempty"`
}

// Operation wrapper for Get_Balance.
// OperationGet_BalanceSoapOut was auto-generated from WSDL.
//<Get_BalanceResponse xmlns="http://tempuri.org/">
type OperationGet_BalanceSoapOut struct {
	Get_BalanceResponse *Get_BalanceResponse `xml:"http://tempuri.org/ Get_BalanceResponse,omitempty" json:"Get_BalanceResponse,omitempty" yaml:"Get_BalanceResponse,omitempty"`
}

// Operation wrapper for Get_CancellationStatus.
// OperationGet_CancellationStatusSoapIn was auto-generated from
// WSDL.
type OperationGet_CancellationStatusSoapIn struct {
	Get_CancellationStatus *Get_CancellationStatus `xml:"Get_CancellationStatus,omitempty" json:"Get_CancellationStatus,omitempty" yaml:"Get_CancellationStatus,omitempty"`
}

// Operation wrapper for Get_CancellationStatus.
// OperationGet_CancellationStatusSoapOut was auto-generated from
// WSDL.
type OperationGet_CancellationStatusSoapOut struct {
	Get_CancellationStatusResponse *Get_CancellationStatusResponse `xml:"Get_CancellationStatusResponse,omitempty" json:"Get_CancellationStatusResponse,omitempty" yaml:"Get_CancellationStatusResponse,omitempty"`
}

// Operation wrapper for Get_ChangeNameStatus.
// OperationGet_ChangeNameStatusSoapIn was auto-generated from
// WSDL.
type OperationGet_ChangeNameStatusSoapIn struct {
	Get_ChangeNameStatus *Get_ChangeNameStatus `xml:"Get_ChangeNameStatus,omitempty" json:"Get_ChangeNameStatus,omitempty" yaml:"Get_ChangeNameStatus,omitempty"`
}

// Operation wrapper for Get_ChangeNameStatus.
// OperationGet_ChangeNameStatusSoapOut was auto-generated from
// WSDL.
type OperationGet_ChangeNameStatusSoapOut struct {
	Get_ChangeNameStatusResponse *Get_ChangeNameStatusResponse `xml:"Get_ChangeNameStatusResponse,omitempty" json:"Get_ChangeNameStatusResponse,omitempty" yaml:"Get_ChangeNameStatusResponse,omitempty"`
}

// Operation wrapper for Get_Forex.
// OperationGet_ForexSoapIn was auto-generated from WSDL.
type OperationGet_ForexSoapIn struct {
	Get_Forex *Get_Forex `xml:"Get_Forex,omitempty" json:"Get_Forex,omitempty" yaml:"Get_Forex,omitempty"`
}

// Operation wrapper for Get_Forex.
// OperationGet_ForexSoapOut was auto-generated from WSDL.
type OperationGet_ForexSoapOut struct {
	Get_ForexResponse *Get_ForexResponse `xml:"Get_ForexResponse,omitempty" json:"Get_ForexResponse,omitempty" yaml:"Get_ForexResponse,omitempty"`
}

// Operation wrapper for Get_ForexNextRate.
// OperationGet_ForexNextRateSoapIn was auto-generated from WSDL.
type OperationGet_ForexNextRateSoapIn struct {
	Get_ForexNextRate *Get_ForexNextRate `xml:"Get_ForexNextRate,omitempty" json:"Get_ForexNextRate,omitempty" yaml:"Get_ForexNextRate,omitempty"`
}

// Operation wrapper for Get_ForexNextRate.
// OperationGet_ForexNextRateSoapOut was auto-generated from WSDL.
type OperationGet_ForexNextRateSoapOut struct {
	Get_ForexNextRateResponse *Get_ForexNextRateResponse `xml:"Get_ForexNextRateResponse,omitempty" json:"Get_ForexNextRateResponse,omitempty" yaml:"Get_ForexNextRateResponse,omitempty"`
}

// Operation wrapper for Get_List.
// OperationGet_ListSoapIn was auto-generated from WSDL.
type OperationGet_ListSoapIn struct {
	Get_List *Get_List `xml:"http://tempuri.org/ Get_List,omitempty" json:"Get_List,omitempty" yaml:"Get_List,omitempty"`
}

// Operation wrapper for Get_List.
// OperationGet_ListSoapOut was auto-generated from WSDL.
type OperationGet_ListSoapOut struct {
	Get_ListResponse *Get_ListResponse `xml:"Get_ListResponse,omitempty" json:"Get_ListResponse,omitempty" yaml:"Get_ListResponse,omitempty"`
}

// Operation wrapper for Get_PayoutCode.
// OperationGet_PayoutCodeSoapIn was auto-generated from WSDL.
type OperationGet_PayoutCodeSoapIn struct {
	Get_PayoutCode *Get_PayoutCode `xml:"Get_PayoutCode,omitempty" json:"Get_PayoutCode,omitempty" yaml:"Get_PayoutCode,omitempty"`
}

// Operation wrapper for Get_PayoutCode.
// OperationGet_PayoutCodeSoapOut was auto-generated from WSDL.
type OperationGet_PayoutCodeSoapOut struct {
	Get_PayoutCodeResponse *Get_PayoutCodeResponse `xml:"Get_PayoutCodeResponse,omitempty" json:"Get_PayoutCodeResponse,omitempty" yaml:"Get_PayoutCodeResponse,omitempty"`
}

// Operation wrapper for Get_TrxFee.
// OperationGet_TrxFeeSoapIn was auto-generated from WSDL.
type OperationGet_TrxFeeSoapIn struct {
	Get_TrxFee *Get_TrxFee `xml:"Get_TrxFee,omitempty" json:"Get_TrxFee,omitempty" yaml:"Get_TrxFee,omitempty"`
}

// Operation wrapper for Get_TrxFee.
// OperationGet_TrxFeeSoapOut was auto-generated from WSDL.
type OperationGet_TrxFeeSoapOut struct {
	Get_TrxFeeResponse *Get_TrxFeeResponse `xml:"Get_TrxFeeResponse,omitempty" json:"Get_TrxFeeResponse,omitempty" yaml:"Get_TrxFeeResponse,omitempty"`
}

// Operation wrapper for Get_TrxStatus.
// OperationGet_TrxStatusSoapIn was auto-generated from WSDL.
type OperationGet_TrxStatusSoapIn struct {
	Get_TrxStatus *Get_TrxStatus `xml:"Get_TrxStatus,omitempty" json:"Get_TrxStatus,omitempty" yaml:"Get_TrxStatus,omitempty"`
}

// Operation wrapper for Get_TrxStatus.
// OperationGet_TrxStatusSoapOut was auto-generated from WSDL.
type OperationGet_TrxStatusSoapOut struct {
	Get_TrxStatusResponse *Get_TrxStatusResponse `xml:"Get_TrxStatusResponse,omitempty" json:"Get_TrxStatusResponse,omitempty" yaml:"Get_TrxStatusResponse,omitempty"`
}

// Operation wrapper for Get_Validation.
// OperationGet_ValidationSoapIn was auto-generated from WSDL.
type OperationGet_ValidationSoapIn struct {
	Get_Validation *Get_Validation `xml:"Get_Validation,omitempty" json:"Get_Validation,omitempty" yaml:"Get_Validation,omitempty"`
}

// Operation wrapper for Get_Validation.
// OperationGet_ValidationSoapOut was auto-generated from WSDL.
type OperationGet_ValidationSoapOut struct {
	Get_ValidationResponse *Get_ValidationResponse `xml:"Get_ValidationResponse,omitempty" json:"Get_ValidationResponse,omitempty" yaml:"Get_ValidationResponse,omitempty"`
}

// Operation wrapper for Get_Watchlist.
// OperationGet_WatchlistSoapIn was auto-generated from WSDL.
type OperationGet_WatchlistSoapIn struct {
	Get_Watchlist *Get_Watchlist `xml:"Get_Watchlist,omitempty" json:"Get_Watchlist,omitempty" yaml:"Get_Watchlist,omitempty"`
}

// Operation wrapper for Get_Watchlist.
// OperationGet_WatchlistSoapOut was auto-generated from WSDL.
type OperationGet_WatchlistSoapOut struct {
	Get_WatchlistResponse *Get_WatchlistResponse `xml:"Get_WatchlistResponse,omitempty" json:"Get_WatchlistResponse,omitempty" yaml:"Get_WatchlistResponse,omitempty"`
}

// Operation wrapper for Ping.
// OperationPingSoapIn was auto-generated from WSDL.
type OperationPingSoapIn struct {
	Ping *Ping `xml:"http://tempuri.org/ Ping,omitempty" json:"Ping,omitempty" yaml:"Ping,omitempty"`
}

// Operation wrapper for Ping.
// OperationPingSoapOut was auto-generated from WSDL.
type OperationPingSoapOut struct {
	PingResponse *PingResponse `xml:"PingResponse,omitempty" json:"PingResponse,omitempty" yaml:"PingResponse,omitempty"`
}

// aPI_Service1Soap implements the API_Service1Soap interface.
type aPI_Service1Soap struct {
	cli *soap.Client
}

// Do_BillInquiry was auto-generated from WSDL.
func (p *aPI_Service1Soap) Do_BillInquiry(Do_BillInquiry *Do_BillInquiry) (*Do_BillInquiryResponse, error) {
	α := struct {
		OperationDo_BillInquirySoapIn `xml:"tns:Do_BillInquiry"`
	}{
		OperationDo_BillInquirySoapIn{
			Do_BillInquiry,
		},
	}

	γ := struct {
		OperationDo_BillInquirySoapOut `xml:"Do_BillInquiryResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Do_BillInquiry", α, &γ); err != nil {
		return nil, err
	}
	return γ.Do_BillInquiryResponse, nil
}

// Do_BillPayment was auto-generated from WSDL.
func (p *aPI_Service1Soap) Do_BillPayment(Do_BillPayment *Do_BillPayment) (*Do_BillPaymentResponse, error) {
	α := struct {
		OperationDo_BillPaymentSoapIn `xml:"tns:Do_BillPayment"`
	}{
		OperationDo_BillPaymentSoapIn{
			Do_BillPayment,
		},
	}

	γ := struct {
		OperationDo_BillPaymentSoapOut `xml:"Do_BillPaymentResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Do_BillPayment", α, &γ); err != nil {
		return nil, err
	}
	return γ.Do_BillPaymentResponse, nil
}

// Do_Cancellation was auto-generated from WSDL.
func (p *aPI_Service1Soap) Do_Cancellation(Do_Cancellation *Do_Cancellation) (*Do_CancellationResponse, error) {
	α := struct {
		OperationDo_CancellationSoapIn `xml:"tns:Do_Cancellation"`
	}{
		OperationDo_CancellationSoapIn{
			Do_Cancellation,
		},
	}

	γ := struct {
		OperationDo_CancellationSoapOut `xml:"Do_CancellationResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Do_Cancellation", α, &γ); err != nil {
		return nil, err
	}
	return γ.Do_CancellationResponse, nil
}

// Do_ChangeName was auto-generated from WSDL.
func (p *aPI_Service1Soap) Do_ChangeName(Do_ChangeName *Do_ChangeName) (*Do_ChangeNameResponse, error) {
	α := struct {
		OperationDo_ChangeNameSoapIn `xml:"tns:Do_ChangeName"`
	}{
		OperationDo_ChangeNameSoapIn{
			Do_ChangeName,
		},
	}

	γ := struct {
		OperationDo_ChangeNameSoapOut `xml:"Do_ChangeNameResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Do_ChangeName", α, &γ); err != nil {
		return nil, err
	}
	return γ.Do_ChangeNameResponse, nil
}

// Do_Transfer was auto-generated from WSDL.
func (p *aPI_Service1Soap) Do_Transfer(Do_Transfer *Do_Transfer) (*Do_TransferResponse, error) {
	α := struct {
		OperationDo_TransferSoapIn `xml:"tns:Do_Transfer"`
	}{
		OperationDo_TransferSoapIn{
			Do_Transfer,
		},
	}

	γ := struct {
		OperationDo_TransferSoapOut `xml:"Do_TransferResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Do_Transfer", α, &γ); err != nil {
		return nil, err
	}
	return γ.Do_TransferResponse, nil
}

// Do_Transfer_Sync was auto-generated from WSDL.
func (p *aPI_Service1Soap) Do_Transfer_Sync(Do_Transfer_Sync *Do_Transfer_Sync) (*Do_Transfer_SyncResponse, error) {
	α := struct {
		OperationDo_Transfer_SyncSoapIn `xml:"tns:Do_Transfer_Sync"`
	}{
		OperationDo_Transfer_SyncSoapIn{
			Do_Transfer_Sync,
		},
	}

	γ := struct {
		OperationDo_Transfer_SyncSoapOut `xml:"Do_Transfer_SyncResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Do_Transfer_Sync", α, &γ); err != nil {
		return nil, err
	}
	return γ.Do_Transfer_SyncResponse, nil
}

// Get_Balance was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_Balance(Get_Balance *Get_Balance) (*Get_BalanceResponse, error) {
	α := struct {
		OperationGet_BalanceSoapIn `xml:"tns:Get_Balance"`
	}{
		OperationGet_BalanceSoapIn{
			Get_Balance,
		},
	}

	γ := struct {
		OperationGet_BalanceSoapOut `xml:"Get_BalanceResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_Balance", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_BalanceResponse, nil
}

// Get_CancellationStatus was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_CancellationStatus(Get_CancellationStatus *Get_CancellationStatus) (*Get_CancellationStatusResponse, error) {
	α := struct {
		OperationGet_CancellationStatusSoapIn `xml:"tns:Get_CancellationStatus"`
	}{
		OperationGet_CancellationStatusSoapIn{
			Get_CancellationStatus,
		},
	}

	γ := struct {
		OperationGet_CancellationStatusSoapOut `xml:"Get_CancellationStatusResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_CancellationStatus", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_CancellationStatusResponse, nil
}

// Get_ChangeNameStatus was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_ChangeNameStatus(Get_ChangeNameStatus *Get_ChangeNameStatus) (*Get_ChangeNameStatusResponse, error) {
	α := struct {
		OperationGet_ChangeNameStatusSoapIn `xml:"tns:Get_ChangeNameStatus"`
	}{
		OperationGet_ChangeNameStatusSoapIn{
			Get_ChangeNameStatus,
		},
	}

	γ := struct {
		OperationGet_ChangeNameStatusSoapOut `xml:"Get_ChangeNameStatusResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_ChangeNameStatus", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_ChangeNameStatusResponse, nil
}

// Get_Forex was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_Forex(Get_Forex *Get_Forex) (*Get_ForexResponse, error) {
	α := struct {
		OperationGet_ForexSoapIn `xml:"tns:Get_Forex"`
	}{
		OperationGet_ForexSoapIn{
			Get_Forex,
		},
	}

	γ := struct {
		OperationGet_ForexSoapOut `xml:"Get_ForexResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_Forex", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_ForexResponse, nil
}

// Get_ForexNextRate was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_ForexNextRate(Get_ForexNextRate *Get_ForexNextRate) (*Get_ForexNextRateResponse, error) {
	α := struct {
		OperationGet_ForexNextRateSoapIn `xml:"tns:Get_ForexNextRate"`
	}{
		OperationGet_ForexNextRateSoapIn{
			Get_ForexNextRate,
		},
	}

	γ := struct {
		OperationGet_ForexNextRateSoapOut `xml:"Get_ForexNextRateResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_ForexNextRate", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_ForexNextRateResponse, nil
}

// Get_List was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_List(Get_List *Get_List) (*Get_ListResponse, error) {
	α := struct {
		OperationGet_ListSoapIn `xml:"tns:Get_List"`
	}{
		OperationGet_ListSoapIn{
			Get_List,
		},
	}

	γ := struct {
		OperationGet_ListSoapOut `xml:"Get_ListResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_List", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_ListResponse, nil
}

// Get_PayoutCode was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_PayoutCode(Get_PayoutCode *Get_PayoutCode) (*Get_PayoutCodeResponse, error) {
	α := struct {
		OperationGet_PayoutCodeSoapIn `xml:"tns:Get_PayoutCode"`
	}{
		OperationGet_PayoutCodeSoapIn{
			Get_PayoutCode,
		},
	}

	γ := struct {
		OperationGet_PayoutCodeSoapOut `xml:"Get_PayoutCodeResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_PayoutCode", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_PayoutCodeResponse, nil
}

// Get_TrxFee was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_TrxFee(Get_TrxFee *Get_TrxFee) (*Get_TrxFeeResponse, error) {
	α := struct {
		OperationGet_TrxFeeSoapIn `xml:"tns:Get_TrxFee"`
	}{
		OperationGet_TrxFeeSoapIn{
			Get_TrxFee,
		},
	}

	γ := struct {
		OperationGet_TrxFeeSoapOut `xml:"Get_TrxFeeResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_TrxFee", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_TrxFeeResponse, nil
}

// Get_TrxStatus was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_TrxStatus(Get_TrxStatus *Get_TrxStatus) (*Get_TrxStatusResponse, error) {
	α := struct {
		OperationGet_TrxStatusSoapIn `xml:"tns:Get_TrxStatus"`
	}{
		OperationGet_TrxStatusSoapIn{
			Get_TrxStatus,
		},
	}

	γ := struct {
		OperationGet_TrxStatusSoapOut `xml:"Get_TrxStatusResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_TrxStatus", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_TrxStatusResponse, nil
}

// Get_Validation was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_Validation(Get_Validation *Get_Validation) (*Get_ValidationResponse, error) {
	α := struct {
		OperationGet_ValidationSoapIn `xml:"tns:Get_Validation"`
	}{
		OperationGet_ValidationSoapIn{
			Get_Validation,
		},
	}

	γ := struct {
		OperationGet_ValidationSoapOut `xml:"Get_ValidationResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_Validation", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_ValidationResponse, nil
}

// Get_Watchlist was auto-generated from WSDL.
func (p *aPI_Service1Soap) Get_Watchlist(Get_Watchlist *Get_Watchlist) (*Get_WatchlistResponse, error) {
	α := struct {
		OperationGet_WatchlistSoapIn `xml:"tns:Get_Watchlist"`
	}{
		OperationGet_WatchlistSoapIn{
			Get_Watchlist,
		},
	}

	γ := struct {
		OperationGet_WatchlistSoapOut `xml:"Get_WatchlistResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Get_Watchlist", α, &γ); err != nil {
		return nil, err
	}
	return γ.Get_WatchlistResponse, nil
}

// Ping was auto-generated from WSDL.
func (p *aPI_Service1Soap) Ping(Ping *Ping) (*PingResponse, error) {
	α := struct {
		OperationPingSoapIn `xml:"tns:Ping"`
	}{
		OperationPingSoapIn{
			Ping,
		},
	}

	γ := struct {
		OperationPingSoapOut `xml:"PingResponse"`
	}{}
	if err := p.cli.RoundTripSoap12("http://tempuri.org/Ping", α, &γ); err != nil {
		return nil, err
	}
	return γ.PingResponse, nil
}
